name: testconfig
spec: 
  listeners:
  - name: listener_0
    address: 0.0.0.0
    port: 9000
    routes:
    - name: fooroute #put more specific route first
      prefix: /foo 
      clusters:
      - foo
    # - name: barroute
    #   prefix: /bar
    #   clusters:
    #   - bar
    - name: echoroute
      prefix: /
      clusters:
      - echo
  clusters:
  - name: foo
    endpoints:
    - address: 127.0.0.1
      port: 9101
    # - address: 127.0.0.1
    #   port: 9102
  # - name: bar
  #   endpoints:
  #   - address: 127.0.0.1
  #     port: 9103
    # - address: 127.0.0.1
    #   port: 9104
  - name: echo
    endpoints:
    - address: 127.0.0.1
      port: 9100
